name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install pipenv
      - name: Run pipenv
        run:
          pipenv install --dev
      - name: Set up PYTHONPATH
        run: |
          # append /home/runner/work/prx/prx/src to PYTHONPATH 
          echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/prx/prx/src" >> $GITHUB_ENV
          echo $GITHUB_ENV
      - name: Lint with flake8
        run: |
         # stop the build if there are Python syntax errors or undefined names
         pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
         pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
         echo "$PWD"
         ls
         echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/prx/prx/src" >> $GITHUB_ENV
         echo $GITHUB_ENV
         pipenv run pytest --durations=10 -k "test_prx_command_line_call_with_csv_output"
